/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pgy.frames;

import com.business.Cliente;
import com.business.Cuenta;
import com.business.Transferencias;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franciscavaldiviapalma
 */
public class HistorialTransf extends javax.swing.JFrame {

    public Cliente cliente = new Cliente();
    public Transferencias transferencias = new Transferencias();

    /**
     * Creates new form HistorialTransf
     */
    public HistorialTransf() {
        initComponents();
    }

    public HistorialTransf(Transferencias transferencias, Cliente cliente) {
        initComponents();
        
        this.cliente = cliente;
        this.transferencias = transferencias;
        load();

    }

    public void load() {
        
        DefaultTableModel model = new DefaultTableModel();
        //Se requiere añadir las columnas de la tabla
        model.addColumn("id_transaccion");
        model.addColumn("cuenta_origen");
        model.addColumn("monto");
        model.addColumn("cuenta_destino");
        model.addColumn("fecha_hora");
        ArrayList<Transferencias> transferencias = new Transferencias().getAll();
        Cuenta cuenta = new Cuenta().obtener(cliente.getCuenta().getNumCuenta());
        for(Transferencias transf : transferencias){
            Object[] row = { transf.getIdTransaccion(), transf.getCuentaOrigen(), transf.getMonto(), transf.getCuentaDestino(), formatoFecha(transf.getFechaHora())};
            if(transf.getCuentaOrigen() == cuenta.getNumCuenta()){
                model.addRow(row);
            }
        }
        tablaHistorial.setModel(model);
    }
    
    
    public String formatoFecha(Date fecha){
        
        SimpleDateFormat DateFor = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        String fechaFormateada = DateFor.format(fecha);
        return fechaFormateada;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menInicio = new javax.swing.JMenu();
        menTransferencia = new javax.swing.JMenu();
        menHistTransf = new javax.swing.JMenu();
        menSalir = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_transaccion", "cuenta_origen", "monto", "cuenta_destino", "fecha_hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaHistorial);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        menInicio.setText("Inicio");
        menInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menInicio);

        menTransferencia.setText("Transferir");
        menTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menTransferenciaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menTransferencia);

        menHistTransf.setText("Historial de Transferencias");
        menHistTransf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menHistTransfMouseClicked(evt);
            }
        });
        jMenuBar1.add(menHistTransf);

        menSalir.setText("Salir");
        menSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menInicioMouseClicked
        
        Inicio frmInicio = new Inicio(cliente);
        frmInicio.setTitle("West Bank");
        frmInicio.setLocation(600, 300);
        frmInicio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmInicio.setVisible(true);
        frmInicio.onLoad();
        this.setVisible(false);
        
    }//GEN-LAST:event_menInicioMouseClicked

    private void menTransferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menTransferenciaMouseClicked
        
        Transferir frmTransferir = new Transferir(cliente);
        frmTransferir.setTitle("West Bank");
        frmTransferir.setLocation(600, 300);
        frmTransferir.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmTransferir.setVisible(true);
        frmTransferir.mostrarNumCuenta();
        this.setVisible(false);
        
    }//GEN-LAST:event_menTransferenciaMouseClicked

    private void menHistTransfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menHistTransfMouseClicked
        
        load();
        
    }//GEN-LAST:event_menHistTransfMouseClicked

    private void menSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menSalirMouseClicked
        
        JOptionPane.showMessageDialog(rootPane, "Ha salido de la aplicación");
        this.setVisible(false);
    }//GEN-LAST:event_menSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialTransf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menHistTransf;
    private javax.swing.JMenu menInicio;
    private javax.swing.JMenu menSalir;
    private javax.swing.JMenu menTransferencia;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
