/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pgy.frames;

import com.business.Cliente;
import com.business.Cuenta;
import com.business.Transferencias;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sebco
 */
public class Inicio extends javax.swing.JFrame {

    public Cliente cliente = new Cliente();
    public Transferencias transferencias = new Transferencias();
   
    

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
    }

    public Inicio(Cliente cliente) {
        initComponents();

        this.cliente = cliente;
        onLoad();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblTextoSaldo = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menInicio = new javax.swing.JMenu();
        menTransferir = new javax.swing.JMenu();
        menHistTransf = new javax.swing.JMenu();
        menSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("West Bank");
        setResizable(false);

        lblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblBienvenido.setText("Bienvenido(a):");

        lblNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNombreCliente.setText("lblNombreCliente");
        lblNombreCliente.setVisible(false);

        lblTextoSaldo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTextoSaldo.setText("Tu saldo es:");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSaldo.setText("$");
        lblSaldo.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBienvenido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTextoSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreCliente)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoSaldo)
                    .addComponent(lblSaldo))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        menInicio.setText("Inicio");
        menInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menInicio);

        menTransferir.setText("Transferir");
        menTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menTransferirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menTransferir);

        menHistTransf.setText("Historial de Transferencias");
        menHistTransf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menHistTransfMouseClicked(evt);
            }
        });
        jMenuBar1.add(menHistTransf);

        menSalir.setText("Salir");
        menSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menTransferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menTransferirMouseClicked
        
        Transferir frmTransferir = new Transferir(cliente);
        frmTransferir.setTitle("West Bank");
        frmTransferir.setLocation(600, 300);
        frmTransferir.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmTransferir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_menTransferirMouseClicked

    private void menInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menInicioMouseClicked
        
        //Se actualiza el saldo
        onLoad();
        
    }//GEN-LAST:event_menInicioMouseClicked

    private void menHistTransfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menHistTransfMouseClicked
        
        //Mostrar historial de transferencias
        HistorialTransf frmHistTransf = new HistorialTransf(transferencias, cliente);
        frmHistTransf.setTitle("West Bank");
        frmHistTransf.setLocation(600, 300);
        frmHistTransf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmHistTransf.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_menHistTransfMouseClicked

    private void menSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menSalirMouseClicked
        
        JOptionPane.showMessageDialog(rootPane, "Ha salido de la aplicación");
        this.setVisible(false);
    }//GEN-LAST:event_menSalirMouseClicked
  
    public void onLoad(){
        
        String nombre = cliente.getNombre();
        String apPaterno = cliente.getApPaterno();
        String apMaterno = cliente.getApMaterno();
        int numCuenta = cliente.getCuenta().getNumCuenta();
        Cuenta cuenta = new Cuenta().obtener(numCuenta);
        int saldoInt = cuenta.getSaldo();
        String saldoStr = String.valueOf(saldoInt);
        lblNombreCliente.setText(nombre + " " + apPaterno + " " + apMaterno);
        lblSaldo.setText("$ " + saldoStr);
        lblNombreCliente.setVisible(true);
        lblSaldo.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTextoSaldo;
    private javax.swing.JMenu menHistTransf;
    private javax.swing.JMenu menInicio;
    private javax.swing.JMenu menSalir;
    private javax.swing.JMenu menTransferir;
    // End of variables declaration//GEN-END:variables
}
